replicaCount: 1
image:
  repository: ghcr.io/your-org/apz-indexer
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 4000
resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
env:
  API_URL: "http://apz-node:26657"
  DATABASE_URL: "postgres://postgres:password@apz-postgres:5432/apz"
persistence:
  enabled: true
  size: 5Gi
  storageClass: ""
nodeSelector: {}
tolerations: []
affinity: {}
