apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apz-indexer.fullname" . }}-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ default "" .Values.persistence.storageClass }}
